image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s maven/settings.xml --batch-mode"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    mvn $MAVEN_CLI_OPTS build
