image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s maven/settings.xml --batch-mode"

cache:
  paths:
    - /build/.m2/
    - /build/target/

build:
  stage: build
  script:
    mvn $MAVEN_CLI_OPTS compile
